name: kepegawaian_lampung_barat
description: "Aplikasi Kepegawaian Kominfo Lampung Barat"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  intl: ^0.20.1
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  dart_jsonwebtoken: ^2.14.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.1.2
  flutter_screenutil: ^5.9.3
  safe_device: ^1.1.9
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  image_picker: ^1.1.2
  syncfusion_flutter_pdf: ^24.1.46
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env
