/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'kepegawaian_lampung_barat';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String FONTS = 'assets/fonts/fonts.dart';
  static const String ICONS = 'assets/icons/icons.dart';
  static const String IMAGES = 'assets/images/images.dart';
}
